### ISSUE TITLE
main.dart报错

### ISSUE THREAD

**Issue by liuchenc** [WinWang/open_eye#6]
![1657114448933](https://user-images.githubusercontent.com/14867909/177562848-98eb0b5c-2a66-4868-859f-3d6030c272ef.jpg)

**Comment by liuchenc** [comment]
![1657204843722](https://user-images.githubusercontent.com/14867909/177801447-cd7844fd-d2f9-4ed3-8fe0-14a0faea880b.jpg)

**Comment by WinWang** [comment]
你应该是GetX框架代码没有依赖拉取到导致的，我本地都是正常的，flutter版本用2.80版本

**Comment by liuchenc** [comment]
apiservice里面封装的不太明白,.g和非.g是不是有重复的地方
