### ISSUE TITLE
有沒方法在bottomBar顯示時上面再推一頁新的

### ISSUE THREAD

**Issue by felix0324324** [WinWang/open_eye#7]
如題，這個demo寫得很好，感謝你

**Comment by WinWang** [comment]
就是bottomBar永远展示在下面？上面的页面能按照正常进出栈加载新页面？？？https://github.com/WinWang/music_listener可以参照我这个音乐播放器的音乐进度条展示模块，在App初始化一个全局的widget，路由放在上面
